// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: process.env['DATABASE_URL'],
    // shadowDatabaseUrl: process.env['DATABASE_URL'],
  },
  migrations: {
    // Point this to your seed file
    seed: 'ts-node ./src/prisma/seed/login-credentials.seed.ts',
  },
});
