import { useState } from "react";
import { useImportPO, useImportHistory } from "@/hooks/purchase-order/useImportPo";
import { ImportResultDisplay } from "@/components/poWokSpace/ImportResultDisplay";
import type { ImportResult, PoImportHistoryItem } from "@/types/po-workspace/types";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, UploadCloud, FileText, History, CheckCircle2, XCircle } from "lucide-react";
import { format } from "date-fns";

export default function PoImportPage() {
  const [file, setFile] = useState<File | null>(null);
  const { mutate, isPending, data } = useImportPO();

  // Call the custom hook with zero arguments—polling logic is managed internally by the hook
  const { data: history = [] } = useImportHistory();

  // ... inside PoImportPage component ...

  const handleUpload = () => {
    if (file) mutate(file, { onSuccess: () => setFile(null) });
  };

  // ✅ Step 1: Extract the active ID generated by your current session's upload action
  const activeJobId = data?.historyId;

  // ✅ Step 2: Cross-reference and pull the real-time record from your polling history array
  const activeHistoryJob = history.find((job) => job.id === activeJobId);

  // ✅ Step 3: Map the banner data from the live history record rather than the static data response
  const formattedResult: ImportResult | null = data
    ? {
        historyId: data.historyId,
        // If the polling data hasn't arrived or is still processing, keep it PENDING.
        // The exact second the database switches to FAILED, the banner updates instantly!
        status: (activeHistoryJob ? activeHistoryJob.status : "PENDING") as "PENDING" | "SUCCESS" | "FAILED",
        duidCount: activeHistoryJob?.duidCount ?? 0,
        poSucceeded: activeHistoryJob?.poCount ?? 0,
        poFailed: activeHistoryJob?.errors?.length ? 1 : 0,
        linesProcessed: activeHistoryJob?.poLineCount ?? 0,
        errors: activeHistoryJob?.errors ?? [],
      }
    : null;

  return (
    <div className="max-w-6xl mx-auto p-8 space-y-12">
      {/* HEADER SECTION */}
      <header className="border-b border-slate-100 pb-6">
        <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Purchase Order Import Dashboard</h1>
        <p className="text-slate-500 mt-1">Upload and reconcile bulk system spreadsheet templates asynchronously.</p>
      </header>

      {/* TOP SECTION: DROPZONE UPLOADER & SCREENER */}
      <div className="grid grid-cols-1 gap-8">
        <div className="border-2 border-dashed border-slate-200 rounded-3xl p-12 flex flex-col items-center justify-center bg-slate-50/50 hover:bg-white hover:border-blue-500 transition-all shadow-sm">
          <div className="h-14 w-14 rounded-full bg-blue-50 flex items-center justify-center mb-4">
            <UploadCloud className="text-blue-600 h-6 w-6" />
          </div>

          <input type="file" id="file-upload" className="hidden" accept=".xlsx,.xls" onChange={(e) => setFile(e.target.files?.[0] || null)} />

          <label htmlFor="file-upload" className="cursor-pointer text-center">
            <span className="text-blue-600 font-bold text-base hover:underline">Click to browse your spreadsheet files</span>
            <p className="text-slate-400 text-xs mt-1">Accepts standard .XLSX / .XLS template data (Max 10MB)</p>
          </label>

          {file && (
            <div className="mt-6 flex items-center gap-4 bg-white p-4 rounded-2xl border border-blue-100 shadow-md min-w-[24rem]">
              <FileText className="text-blue-500 h-5 w-5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold text-slate-900 truncate">{file.name}</p>
                <p className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">{(file.size / 1024).toFixed(1)} KB</p>
              </div>
              <Button onClick={handleUpload} disabled={isPending} className="bg-blue-600 hover:bg-blue-700 rounded-xl px-5">
                {isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Process Data"}
              </Button>
            </div>
          )}
        </div>

        {/* IMMEDIATE ACTION RESULTS STATUS BLOCK */}
        {formattedResult && <ImportResultDisplay data={formattedResult} />}
      </div>

      {/* LOWER SECTION: CLEAN DATA HISTORY LOG TABLE */}
      <section className="bg-white border border-slate-200/80 rounded-3xl p-6 shadow-sm space-y-6">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-4">
          <History className="size-5 text-slate-400" />
          <div>
            <h2 className="font-bold text-sm text-slate-800">Historical Import Logs</h2>
            <p className="text-xs text-slate-400">Complete execution audits of uploaded templates.</p>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-100 overflow-hidden bg-white">
          <Table>
            <TableHeader className="bg-slate-50/70">
              <TableRow>
                <TableHead className="font-semibold text-slate-600 text-xs w-[40%]">File Name</TableHead>
                <TableHead className="font-semibold text-slate-600 text-xs">Date Triggered</TableHead>
                <TableHead className="font-semibold text-slate-600 text-xs text-center">Status</TableHead>
                <TableHead className="font-semibold text-slate-600 text-xs text-right">DUIDs</TableHead>
                <TableHead className="font-semibold text-slate-600 text-xs text-right">Total POs</TableHead>
                <TableHead className="font-semibold text-slate-600 text-xs text-right">Processed Lines</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {history.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-12 text-slate-400 text-sm">
                    No historical logs matching this workspace profile found.
                  </TableCell>
                </TableRow>
              ) : (
                history.map((item: PoImportHistoryItem) => (
                  <TableRow key={item.id} className="hover:bg-slate-50/50 transition-colors">
                    <TableCell className="font-medium text-slate-900 text-sm truncate max-w-xs">{item.fileName}</TableCell>
                    <TableCell className="text-slate-500 text-xs">{format(new Date(item.createdAt), "MMM dd, yyyy • HH:mm")}</TableCell>
                    <TableCell className="text-center">
                      <div className="flex justify-center">
                        <StatusIcon status={item.status} />
                      </div>
                    </TableCell>
                    <TableCell className="text-right text-slate-600 font-mono text-xs">{item.duidCount}</TableCell>
                    <TableCell className="text-right text-slate-600 font-mono text-xs">{item.poCount}</TableCell>
                    <TableCell className="text-right text-slate-600 font-mono text-xs">{item.poLineCount}</TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </section>
    </div>
  );
}

function StatusIcon({ status }: { status: string }) {
  if (status === "PENDING") {
    return (
      <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-50 text-blue-700 text-[10px] font-bold tracking-wide uppercase border border-blue-100">
        <Loader2 className="size-3 animate-spin" />
        Processing
      </div>
    );
  }
  if (status === "SUCCESS") {
    return (
      <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 text-[10px] font-bold tracking-wide uppercase border border-emerald-100">
        <CheckCircle2 className="size-3" />
        Success
      </div>
    );
  }
  return (
    <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-red-50 text-red-700 text-[10px] font-bold tracking-wide uppercase border border-red-100">
      <XCircle className="size-3" />
      Failed
    </div>
  );
}
