export const PERMISSION_CODES = {
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  DISABLE_USER: "DISABLE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USERS: "VIEW_USERS",

  CREATE_PO: "CREATE_PO",
  EDIT_PO: "EDIT_PO",
  DELETE_PO: "DELETE_PO",
  VIEW_PO: "VIEW_PO",

  EDIT_CONTRACT: "EDIT_CONTRACT",
  APPROVE_FUNDS_REQUEST: "APPROVE_FUNDS_REQUEST",
  CREATE_FUNDS_REQUEST: "CREATE_FUNDS_REQUEST",
  VIEW_REPORTS: "VIEW_REPORTS",
} as const;

export const ROLE_NAMES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  PM: "PM",
  PD: "PD",
  MD: "MD",
} as const;

export const PO_AGING_THRESHOLD = 21; // days

export const PROJECT_NAMES = [
  "MTN",
  "GLO",
  "AIRTEL",
  "9MOBILE",
  "OTHERS",
] as const;
